### ISSUE TITLE
Build fails with "invalid argument"

### ISSUE THREAD

**Issue by danielneis** [playlyfe/docker-moodle#1]
Hello,

i've cloned the repository and tried to use this docker image but it failed on ./build.sh step.
Here is what i've done and the outputs:
root@sheena:/home/neis/docker-moodle# ./build.sh 
Sending build context to Docker daemon 146.9 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:trusty
 ---> 9cbaf023786c
Step 1 : MAINTAINER Peter John peter@playlyfe.com
2015/04/17 14:36:53 invalid argument
root@sheena:/home/neis/docker-moodle# echo $?
1

Can you help?

Kind regards,
Daniel

**Comment by ghost** [comment]
I don't know what could be wrong. It seems everything is working fine in my system. Can you give me more information on the OS and docker version you are using?

**Comment by danielneis** [comment]
Hello,

i am using Debian version 8.0 Jessie
and Docker version 1.3.3, build d344625

**Comment by ghost** [comment]
Can you try 
`docker build --tag="playlyfe/moodle:latest" .`
within the same folder I think something is wrong with the bash script.

**Comment by danielneis** [comment]
root@sheena:/home/neis/docker-moodle# docker build --tag="playlyfe/moodle:latest" .
Sending build context to Docker daemon 146.9 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:trusty
 ---> 9cbaf023786c
Step 1 : MAINTAINER Peter John peter@playlyfe.com
2015/04/23 09:40:43 invalid argument
