### ISSUE TITLE
The page don't works

### ISSUE THREAD

**Issue by snowc0de** [playlyfe/docker-moodle#4]
Hello!

I have just installed it using your instructions but when I go to http://localhost:3000/
Something happen: 
![Screenshot from 2019-08-12 19-14-59](https://user-images.githubusercontent.com/33733474/62883918-8a235b00-bd35-11e9-9f55-728ba963baf2.png)

Thanks in advance

Chopin

**Comment by kumarharsh** [comment]
Sorry to disappoint you, but we haven't use this in a long long time, and aren't supporting this. I'll archive the repository now as it'll cause more harm than help. There's a good Moodle image from the official source: https://github.com/moodlehq/moodle-docker
